language: python
python:
- '2.7'
cache:
  apt: true
  directories:
  - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages
install:
- pip install -U pip
- pip --version
- mkdir -p /tmp/hivelocity-shared
- pushd /tmp/hivelocity-shared
- git init
- git remote add origin git@github.com:hivelocity/hivelocity-shared.git
- export TRAVIS_BRANCH=`[ "$TRAVIS_PULL_REQUEST" != "false" ] && curl -s https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST?access_token=$GITHUB_OAUTH_TOKEN
  | python -c 'import json; import sys; j = json.load(sys.stdin); print j["head"]["ref"]'
  || echo $TRAVIS_BRANCH`
- export HIVSH_BRANCH=`git ls-remote --heads origin | cut -f 2 | sed -n 's/refs\/heads\/\(.*\)/\1/p'
  | grep -q "$TRAVIS_BRANCH" && [ $? ] && echo $TRAVIS_BRANCH || echo master`
- popd
- pip install -e git+ssh://git@github.com/hivelocity/hivelocity-shared.git@$HIVSH_BRANCH#egg=hivelocity-shared
- pip install `grep -Ev '^#|hivelocity-shared' reqs/base.txt`
- pip install `grep -Ev '^\-r' reqs/dev.txt`
before_install:
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- md5sum ~/.ssh/id_rsa
- killall ssh-agent
- eval `ssh-agent -s`
- ssh-add
script: PYTHONPATH=. py.test -v
env:
  global:
  - secure: cpToDzmcMpjeHVYCRvaI9z6OFDC5egm3C2QIpvjgKm7d/dlBGKec+R804fCHhRPO79tBcfsuzuO7DymwdKbtwGqE8FVKq30nuhuHpx2s8GRBKSWNtor0LBB/NNJhhuY2FJSv/te+HtEB/0rcLFd2v+N7SIE4C1M3Mj2q7HClO64=
  - secure: GXQ0Vjr93EbWAMAyyMtlaubSxd/TwgW2kGmPCgzSD4J3WcIX7ftctpwXHMpS6zSl8bmDDvOva3k86yBnxs3f7VTTTXOy9+R5dvRCuHxQlMVCbjievfVkEVQkzb/zN6LU2J9jVAD6cpcjE/QxpZBKx9qxPyzjRrMZbGfu4tutHfA=
  - secure: mTQRVyK8LJ46uwf/KsWKIh1qliIw/okCKwP2hnsLGm91fpjWV6GYCzGb4CPJ9jHdDSzGycogLFNMBnw3udlgHeppgk/opqHidu/WhzAxIACc3gTfAAWNE/gJmhZUH28Ea9qoUKqfA/ZLTT0RNcO8rrpH3xJtbXVFD+PVOwVKbkQ=
  - secure: CahRGoamI5nqSp0MoW1ScmbIv9ImhTy1U8heBHOjzCahe/ohB4dhdrXwgT43xS9/LAwHOHxFNVRo5nMWEQ/s+/MqKohygU2zTxw9DLYFbjFPZUvIVcQY6oybgjKzNwlelv/+Tv4h3nXuT7uVPTqho9NDizCBSbIEUuCfBHPQzEo=
  - secure: V83nGGjhs8CKLel8tDu8LEeN+VyctjYdtg2fdPq++7d8qrvwxYa0tnXiGJ3+/zJIe5RUuCG1qRhpcmZOzjSkDTIUZFVtVfIsb3MF4x3pRoX76R8osBY5jsvvJIRG04ZS+sZsTZobrDXJG2Q177d5jZFo4/aNcOw/v4Erj0U+KTs=
  - secure: OlVbLbaPlEDgHZLJbkEaGbmT8HJ67ThqwlVNY45jCoqh8kgIP15tyaiW8WODwNAO+Q3++TVb582x6PszJC2oGwuoldIFWWJpLu/XIl50f7uqwvrs1HFcdk21vt0i/tCFWNq9rYETLdvf7EO7E5BsvrxYkdyVNVm7DGjFNYsC+1A=
  - secure: WQXbReR/1c4pcjVF8CAn/a3/dlXzA7aMNx2V3LxWv4gOpmm+pq0q8LaTqWKAN4I8D5siuYCjTq/G1ukLehq+oO596Dg7XHi8b8xJqTUz4KSVKJj2bJWKejhEUXjBHM3sJ1If0zjQEnT7AgGaFicbBRm99X2mYVVZ85V1lGu7a98=
  - secure: MR8aACXhQf+3XM902dLTJE8MYGGQ7r8YXypeGgCb1I0D8atHE8Y8k5HbrPClMW4aVMKIAgdzwklfdkhE+vAgFQ5g+zohr+R5lUtjSILwkF0i1oc4O/y0PuFA6KQhJvWQ08xzb5IVv8OcXpfHs85a91BseRzn1V8i9EH7ttuvA/Y=
  - secure: bWlS9e825DrEOIdWgqP48F3yTDxs6cuwPpOK5p+vnVLAEf9JAQBFr+UcicpuXiWq6t7Q10E15UPfDnVQt4Dt4nhs3VV4wumJydJY9RCdnWC71neBaHR+jRi82REs1ZjYgdCkOqdPGzHjXwzJCI4ECBFHy9+R4C+lbNL7uKy9V6s=
  - secure: UYD9bncKy7Kd6sfHbd7CR2K4g+urDOxFoka60NPtB8/90xL2N4DFEAMk2SjJ61v4XsEMOJv8AuYMnuuvuKLn1TPoE7TsgYd160FW58H3KML4tYffPtrHbDYr4Qbh+S1dYkxM9l6sVS11AdoEtgYkxRSDvk3tv9KeT/9KgXiE6Y4=
  - secure: lXWulMfwd4Q6jbVBAIrkgJ6ImuwL9yIkoSOiQ3wFMO60k5BJ0Pi5SPHrgZUOPbF3KbhgMxbVT3BfsmnPCzjbiXWnGoNVOVouMHRXuUAS4fx0z6nDVzdu4Wn7nQyWlH4XJQlXlNz+eIL6HSFUrXQAi262hckPbAmB9ogdY6ogzJE=
  - secure: CelcVyWZkoAN3nrCjhbQ6RPrfxb+KCqHkB1iwDlNeoAC5rdhwqT956la49Sg3Gz8fZ2o4jI02x8ni7GlDfszzIOqMyuRQMz5YSkJZNpFncOKvaqvrio+YgPhSy/uE3Q/a/YYx2xcode/YZBC+h/L5zijHPEEdnPRPZEwIIsBt8M=
  - secure: Twgs0pC5xA0U8cmf9YG/6ozAKKx44/OOLGDBrSqeUgW8njDm4vYvaBlqohY2VfcKZnmgHa2k0XM+Zl7RsGYI62HuaEf4WXgswe9IP8vDLROfHaFvRMvEXSMv3Ua83t91fRwoNUNQ/yCBfPneuOTXITGiSg/1/Jm6Czpi5vhXAC0=
  - secure: X8IuH//FoY9zGQD8HJQoZlDSbHI/9oZaABK3mYPvrC0MLg4Hc4IqyxE4LVsT3Hdd44vxlC/dnRxIsMYP7cRPCUqKiy85a5l2phuVW0Rn/tDqK64FzAwvYOg45vqu99Nyq12640niW7TbmdC7lYxr6JZRO5WQ6r4swuky9EsD1g4=
  - secure: H8lrNpgv/VCVgZyW183Sjvjtu4V2Y5MnJOZefykYcOp1BTJ7LBXfkLiDKzFW9Y9lUIozhADxZUJWE7fsZ/Fgawmvb4LsHkTpDmJJp/QzengsVgjg7TNAn1mj7vSbJSznWgGeuYsvU+kQzm9/q0YKIujy7Qt9SdJ0uwKWLhl4phc=
  - secure: SzzLCtaqUIsJbmGkclTSN5pQtlmdgfH4S/ksKHRQnPZfGaKQrOquMfvWIIN6yz0qvzSnPlNg6Pr8Mf2yuixyTOZf32M1gnSTU6o9DQKFHFZqzeTUY8NDT9MYbSZ2tfU1zGpNDdzxKUfanwc4FWCNrfQ8NP4niEqWfO8ziWt/hHc=
  - secure: HbV+KTy02H+cLUkiW2mJTzmOAlAMQc5hQLpBwm/i5EZUXeFYxCfT3bibbLiCdVhpy2RFpPVHLNqoiV3yVvc/bkNrpWaW8fzdTfPcAIjxITTmZvXB+VvLQ9shDyPP7n8FhnUEYVf+aN7he13sKIQbUCnPTaf1NFvG1aAntQSHGKU=
  - secure: nPj2XXRyla9uX8hYkbC+WSDK+WSMjeXRSsOMjUzipiMSIo2A81RJi7Dbs/SblZTDjNpSNNe82D0B1oOodFGd0L0ISWe1/IfLpnG7FJMk0jg72y+tM8UWIiHUw8L5UiSEdf9Ug5ji1sXXBdXXN+HdKxH4kjeefHngj1AU8fzfbCU=
  - secure: k31O2EnqWbrGVvVUqucarvRngbPoidC48dTxA1vfpJ3dqaVNHV1040O8wXLSXQYthmo5RoaMULy+DjkDLpK84kPZ02C6NaVEtlLouT5fvwYTHITwzCW6WSxnsMSNA7lBzMlKUw/oWaPNYgbwQ7A8W9jg2GJk4kg1ZoGJ2B+7pTQ=
  - secure: DSdklVBn1aVdXyEuCRJKdP/FUXtxCqOcsVo6zH1yiR/xcvPzONamXkDSHdnNos5xHhxqOD2+y4bheJe9BBP5NAYTnrdyZbVrlM0RkVy3YGzkpeBXKIzNkRY0aJy5gueN3XKRS8DIEhact5Zo/OCcnNCSaBW7QhkcB9I49Cl2/Sw=
  - secure: W3CO9SxjyoKBFrXclNR2rXsSx3RcB+oNGQFJpX7Mh+U8CktNB00mSl1JjQVJk4k5WPiQDlUbMqtOwR9hOruMKkTj2o9Tun7h2myp8lCtH2CV+z+tzarTIK2+1hFEfjLVdJR4V/4PMqrA5nW0x7+kNCe0f5+w4QJRQkYkiRIk1zY=
  - secure: VoMLTFfMm5+Q0Mso6+zhvCho8q5LmYJoJ3nK8mLmKZRaBB6tpKvNmIG86MlnM9ApmB43b8i1ZdDovKT6QfeJC2KSldeWtsQtKUWiIGZF5ZvzZkY7aLD8hDid0YBPBU39WKfaIWjB/VEweJs4Dc5cXvwyvnPErCWWGAHaVbv14d8=
  - secure: DImQhdwq9pOxqW5HhjKQDh8YtoHRAq1u+7YjmxbFbRItXnmUOo+rlRJWSaYbZSe4ja5y1Ir0kP0wMDHRIAjxjJIaooieIa3OA7dhIgE0MOB9BzI7Px2kBKzVP9ono0dqnBDSFQLdIobBxjY61r38CYszEkv2fJeTpE6ptW8f0sU=
  - secure: OrXeX3F7AdT4eYjTgHwyvlyzLAzqM1YzX84WR4c7AxAKZB+1FTtwhpCKTvac2dLELrL2ylDFh6vAC/KWLipV83IHpChxuPj0WfpJwrnk3Xjximc1wsrUNgeQ8uZdWFKPE/oHu4h6r4489yPqcbGIcVTN9nfqy8T7YIzEs9KhxQ4=
notifications:
  hipchat:
    rooms:
      secure: dmk55ZzTxJN6A5Vb1i8mwEd22NEdrTg/ESPz7U1XKxy2kd/Y15exzjSWpwbVhhJN3mjTvzUwiCNI6wL1Yqi4Cog6SxoL3pBShRQSThLWHiht75w1zzlbnw4eccPjOTq2rDUCCse8enVwn5mpujL56mpvxJ3pWZIvvsOvBd7qzKs=
    template:
    - '%{repository} build #%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
